---

- name: Create service user
  user:
    name: svc_geth
    shell: /usr/sbin/nologin
    createhome: no
  ignore_errors: true

- name: Ensure nobody group exists
  group:
    name: nobody
    state: present

...
