---

- name: Converge
  hosts: all
  tasks:
    - name: Install geth dependancies
      include_role:
        name: geth
    - name: Bootstrap geth genesis and wallets
      include_role:
        name: geth
        tasks_from: linux/common/bootstrap.yml

...
