---
# tasks file for lighthouse
- name: Download and Install Precompiled Binary
  hosts: lighthouse_clients
  become: yes
  tasks:

    - name: Download tar.gz file
      get_url:
        url: "https://github.com/sigp/lighthouse/releases/download/v5.0.0/lighthouse-v5.0.0-x86_64-unknown-linux-gnu-portable.tar.gz"
        dest: "/tmp/lighthouse-5.0.0.tar.gz"

    - name: Extract tar.gz file
      unarchive:
        src: "/tmp/lighthouse-5.0.0.tar.gz"
        dest: "/opt/lighthouse-5.0.0"
        remote_src: yes
        extra_opts: "--strip-components=1"

    - name: Ensure binary is executable
      file:
        path: "/opt/lighthouse-5.0.0/lighthouse"
        mode: "u+x"

    - name: Add binary to system path
      file:
        src: "/opt/lighthouse-5.0.0/lighthouse"
        dest: "/usr/local/bin/lighthouse"
        state: link
