---
network_interfaces:
  - name: enp0s3
    dhcp: true
  - name: enp0s8
    dhcp: false
    ip_address: 192.168.196.102
    cidr: 24
    gateway: 192.168.196.1
    nameservers:
      - 8.8.8.8
      - 8.8.4.4
...
