---

- name: Create service user svc_geth
  import_tasks: "linux/common/create_svc_user.yml"

- name: Create directory structure under root_dir
  import_tasks: "linux/common/create_directory_structure.yml"

- name: Deploy tooling scripts
  import_tasks: "linux/common/deploy_tooling.yml"

- name: Check if the OS is Ubuntu
  set_fact:
    is_ubuntu_geth: "{{ ansible_distribution == 'Ubuntu' }}"
  when: ansible_distribution == 'Ubuntu'

- name: Include Ubuntu tasks
  include_tasks: "linux/Ubuntu/main.yml"
  when: is_ubuntu_geth

- name: Bootstrap node
  include_tasks: "linux/common/bootstrap.yml"

- name: Configure services
  include_tasks: "linux/common/config.yml"

- name: Start geth
  include_tasks: "linux/common/create_geth_svc.yml"

...
