---

- name: Converge all geth install
  hosts: all
  tasks:

    - name: Install geth dependancies
      include_role:
        name: geth

- name: Converge bootstrap
  hosts: "{{ groups['multi_node_validator'][0] }}"
  tasks:

    - name: Bootstrap wallet
      include_role:
        name: geth
        tasks_from: linux/common/bootstrap.yml

- name: Converge sync
  hosts: all
  gather_facts: yes
  tasks:

    - name: Sync genesis
      include_role:
        name: geth
        tasks_from: linux/common/sync.yml
      vars:
        bootstrap_node: "{{ groups['multi_node_validator'][0] }}"

...
