---

- name: Write genesis configuration to JSON file
  become: yes
  copy:
    content: "{{ genesis_config | to_json }}"
    dest: "{{ root_dir }}/genesis/genesis.json"
    owner: svc_geth
    group: root
    mode: 0660

- name: Write keystore files to disk
  become: yes
  copy:
    content: "{{ item.value | to_nice_json }}"
    dest: "{{ item.key }}"
    owner: svc_geth
    group: root
    mode: "0660"
  loop: "{{ validator_keystore | dict2items }}"

- name: Iterate over keystore variable and write keyfile content
  include_tasks: linux/common/write_keyfile.yml
  vars:
    keystore_item: "{{ item }}"
  loop: "{{ keystore | dict2items }}"
  loop_control:
    loop_var: item

- name: Change keystore ownership
  become: yes
  command: "chown -R svc_geth:root {{ root_dir }}/ethereum/keystore"
    
- name: Change permissions
  become: yes
  command: "chmod -R 770 {{ root_dir }}/ethereum/keystore"

- name: Initialize genesis block
  become: yes
  command: "geth --datadir {{ root_dir }}/ethereum init {{ root_dir }}/genesis/genesis.json"
  ignore_errors: yes

- name: Create list of wallet passwords
  set_fact:
    passwords_list: "{{ gen_wallets | map(attribute='password') | list }}"

- name: Delete passwords file for unlock
  become: yes
  file:
    path: "{{ root_dir }}/ethereum/passwords.txt"
    state: absent
  ignore_errors: yes

- name: Write wallet passwords to file
  become: yes
  lineinfile:
    path: "{{ root_dir }}/ethereum/passwords.txt"
    line: "{{ item }}"
    create: yes
    mode: "0660"
    owner: svc_geth
    group: root
  loop: "{{ passwords_list }}"

- name: Change ownership and permissions of a directory recursively
  become: yes
  file:
    path: "{{ root_dir }}/ethereum"
    recurse: yes
    owner: svc_geth
    group: root
    mode: "770"

...
