---

- name: Copy geth-boot.service template
  become: yes
  template:
    src: geth-boot.service.j2
    dest: /lib/systemd/system/geth-boot.service

- name: Copy geth.service template
  become: yes
  template:
    src: geth.service.j2
    dest: /lib/systemd/system/geth.service

- name: Reload daemon
  become: true
  systemd:
    daemon_reload: true

- name: Enable geth-boot.service
  become: yes
  systemd:
    name: geth-boot
    enabled: yes
    state: started

- name: Enable geth.service
  become: yes
  systemd:
    name: geth
    enabled: yes
    state: started

...
