---

- name: Get matching addresses in gen_wallets
  set_fact:
    matching_wallet: "{{ gen_wallets | json_query('[?address == `' + keystore_item.key + '`]') | first }}"
  when: matching_wallet is not none

- name: Create keyfile directory if it doesn't exist
  become: yes
  file:
    path: "{{ matching_wallet.keyfile_path | dirname }}"
    state: directory
    owner: svc_geth
    group: root
    mode: 770
  when: matching_wallet is defined

- name: Write keyfiles
  become: yes
  copy:
    content: "{{ keystore_item.value }}"
    dest: "{{ matching_wallet.keyfile_path }}"
    owner: svc_geth
    group: root
    mode: 0660
  when: matching_wallet is defined

...
