---
- name: Install required packages
  hosts: your_host
  become: yes
  tasks:
    - name: Install packages
      apt:
        name:
          - python3
          - python3-pip
          - jq
          - net-tools
        state: present

- name: Run install script for web3 tooling
  hosts: all
  become: yes
  tasks:
    - name: Execute install script
      command: "curl -LSs https://raw.githubusercontent.com/gochain/web3/master/install.sh | sh"
...
