---
- name: reboot_wait
  hosts: all
  tasks:

    - name: Trigger reboot
      ansible.builtin.reboot:
        reboot_timeout: 300
        pre_reboot_delay: 0

    - name: Wait for host to come back after reboot
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: Wait for SSH to become available after reboot
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10
        timeout: 300
      become: false
      when: reboot_required.rc == 0 and reboot_required.stdout != ""

    - name: Verify SSH connectivity after reboot
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10
        timeout: 300

    - name: Continue provisioning tasks after reboot
      ansible.builtin.debug:
        msg: "Device is back up, continuing with provisioning"
