---

- name: Copy geth.tgz to root_dir/src/
  become: yes
  ansible.builtin.copy:
    src: "files/linux/{{ ansible_architecture }}/Ubuntu/{{ ansible_distribution_version }}/geth-{{ geth_version | default('geth_version') }}.tgz"
    dest: "{{ root_dir | default('root_dir') }}/src/"
    remote_src: false

- name: Extract geth.tgz to root_dir/src/
  become: yes
  ansible.builtin.unarchive:
    src: "{{ root_dir | default('root_dir') }}/src/geth-{{ geth_version | default('geth_version') }}.tgz"
    dest: "{{ root_dir | default('root_dir') }}/src"
    remote_src: yes
    creates: "{{ root_dir | default('root_dir') }}/src/geth"

- name: Set file ownership and permissions for root_dir/src/geth
  become: yes
  ansible.builtin.file:
    path: "{{ root_dir | default('root_dir') }}/src/geth"
    owner: svc_geth
    group: root
    mode: "0750"

- name: Create symlink /usr/local/bin/geth
  become: yes
  ansible.builtin.file:
    src: "{{ root_dir | default('root_dir') }}/src/geth"
    dest: /usr/local/bin/geth
    state: link

- name: Ensure dirmngr is installed (gnupg dependency).
  become: yes
  apt:
    name: dirmngr
    state: present

- name: Add Ethereum PPA repository
  become: yes
  apt_repository:
    repo: "ppa:ethereum/ethereum"
    state: present

- name: Install bootnode package
  become: yes
  apt:
    name: bootnode
    state: present
    update_cache: yes
    install_recommends: no
    force_apt_get: yes
    dpkg_options: 'force-confnew'
    update_cache: yes
    allow_unauthenticated: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

...
