---

- name: Create service user svc_geth
  import_tasks: "linux/common/create_svc_user.yml"

- name: C reate directory structure for lighthouse
  import_tasks: "linux/common/create_directory_structure.yml"

- name: Check if the OS is Ubuntu
  set_fact:
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
  when: ansible_distribution == 'Ubuntu'

- name: Include Ubuntu tasks for lighthouse
  include_tasks: "linux/Ubuntu/main.yml"
  when: is_ubuntu

- name: Bootstrap lighthouse enr
  include_tasks: "linux/common/bootstrap.yml"

- name: Generate lighthouse testnet
  include_tasks: "linux/common/generate_testnet.yml"

- name: Start lighthouse services
  include_tasks: "linux/common/create_lighthouse_svc.yml"

...
