---

- name: Create root directory
  become: yes
  file:
    path: "{{ root_dir | default('root_dir') }}"
    state: directory
    owner: svc_geth
    group: root
    mode: "770"

- name: Create lighthouse data directory
  become: yes
  file:
    path: "{{ root_dir | default('root_dir') }}/ethereum/lighthouse"
    state: directory
    owner: svc_geth
    group: root
    mode: "770"
    recurse: yes

- name: Create lighthouse testnet directory
  become: yes
  file:
    path: "{{ root_dir | default('root_dir') }}/ethereum/lighthouse/testnet"
    state: directory
    owner: svc_geth
    group: root
    mode: "770"
    recurse: yes

- name: Create src directory
  become: yes
  file:
    path: "{{ root_dir | default('root_dir') }}/src"
    state: directory
    owner: svc_geth
    group: root
    mode: "770"

...
