---

- name: Copy lighthouse-boot.service template
  become: yes
  template:
    src: lighthouse-boot.service.j2
    dest: /lib/systemd/system/lighthouse-boot.service

- name: Copy lighthouse.service template
  become: yes
  template:
    src: lighthouse.service.j2
    dest: /lib/systemd/system/lighthouse.service

- name: Copy lighthouse-vc.service template
  become: yes
  template:
    src: lighthouse-vc.service.j2
    dest: /lib/systemd/system/lighthouse-vc.service

- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: true

- name: Recursively change ownership and mode of /opt/validator directory
  become: yes
  file:
    path: "{{ root_dir | default(root_dir) }}"
    owner: svc_geth
    group: root
    mode: "770"
    recurse: yes
    state: directory

- name: Start lighthouse_boot.service
  become: yes
  systemd:
    name: lighthouse-boot
    enabled: yes
    state: restarted

- name: Start lighthouse.service
  become: yes
  systemd:
    name: lighthouse
    enabled: yes
    state: restarted

- name: Start lighthouse_vc.service
  become: yes
  systemd:
    name: lighthouse-vc
    enabled: yes
    state: restarted

...
