---

- name: Copy lighthouse-boot.service template
  become: yes
  template:
    src: lighthouse-boot.service.j2
    dest: /lib/systemd/system/lighthouse-boot.service

- name: Copy lighthouse.service template
  become: yes
  template:
    src: lighthouse.service.j2
    dest: /lib/systemd/system/lighthouse.service

- name: Copy lighthouse-vc.service template
  become: yes
  template:
    src: lighthouse-vc.service.j2
    dest: /lib/systemd/system/lighthouse-vc.service

- name: Reload daemon
  become: true
  systemd:
    daemon_reload: true

- name: Recursively change ownership and mode of /opt/validator directory
  become: yes
  file:
    path: "{{ root_dir | default(root_dir) }}/ethereum/bootstrap_enr"
    owner: svc_geth
    group: root
    mode: "0660"
    recurse: yes
    state: directory

- name: Recursively change ownership and mode of /opt/validator directory
  become: yes
  file:
    path: "{{ root_dir | default(root_dir) }}/ethereum/node_1"
    owner: svc_geth
    group: root
    mode: "0660"
    recurse: yes
    state: directory

- name: Recursively change ownership and mode of /opt/validator directory
  become: yes
  file:
    path: "{{ root_dir | default(root_dir) }}/ethereum/testnet"
    owner: svc_geth
    group: root
    mode: "0660"
    recurse: yes
    state: directory

- name: Enable lighthouse-boot.service
  become: yes
  systemd:
    name: lighthouse-boot
    enabled: yes
    state: started

- name: Enable lighthouse.service
  become: yes
  systemd:
    name: lighthouse
    enabled: yes
    state: started

- name: Enable lighthouse-vc.service
  become: yes
  systemd:
    name: lighthouse-vc
    enabled: yes
    state: started

...
