---

- name: Update apt cache
  apt:
    update_cache: yes

- name: Perform forced non-interactive upgrade
  apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
    force_apt_get: yes
    dpkg_options: 'force-confnew'
    install_recommends: no
    update_cache: yes
    allow_unauthenticated: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

...
