---

- name: Ensure netplan directory exists
  ansible.builtin.file:
    path: /etc/netplan
    state: directory

- name: Generate Netplan configuration file
  template:
    src: 00-installer-config.yml.j2
    dest: /etc/netplan/00-installer-config.yaml
  become: yes
  check_mode: no

...

