---

- name: Converge clean all
  hosts: all
  tasks:

    - name: Bootstrap clean
      include_role:
        name: geth
        tasks_from: linux/common/clean.yml

- name: Single node bootstrap
  hosts: "{{ groups['all'][0] }}"
  tasks:
    - name: Bootstrap node
      include_role:
        name: geth

- name: Sync
  hosts: all
  tasks:

    - name: Sync facts
      include_role:
        name: geth
        tasks_from: linux/common/sync.yml
      vars:
        bootstrap_node: "{{ groups['all'][0] }}"

- name: Generate geth cluster
  hosts: all
  tasks:
    - name: Generate geth cluster
      include_role:
        name: geth

- name: Install and config lighthouse
  hosts: all
  tasks:
    - name: Install and config lighthouse
      include_role:
        name: lighthouse


...
