---

- name: Converge all geth install
  hosts: all
  tasks:

    - name: Install geth dependancies
      include_role:
        name: geth

- name: Converge bootstrap
  hosts: "{{ groups['all'][0] }}"
  tasks:

    - name: Bootstrap wallet
      include_role:
        name: geth
        tasks_from: linux/common/bootstrap.yml

- name: Converge sync
  hosts: all
  gather_facts: yes
  tasks:

    - name: Sync facts
      include_role:
        name: geth
        tasks_from: linux/common/sync.yml
      vars:
        bootstrap_node: "{{ groups['all'][0] }}"

- name: Converge config
  hosts: all
  tasks:

    - name: Config genesis
      include_role:
        name: geth
        tasks_from: linux/common/config.yml

- name: Converge svc
  hosts: all
  tasks:

    - name: Enable genesis
      include_role:
        name: geth
        tasks_from: linux/common/create_geth_svc.yml

...
